-- ══════════════════════════════════════════════════════════════
-- V1__init.sql
-- 왜: ddl-auto: create-drop으로 8개 엔티티(실제 물리 테이블 9개,
--     GithubRepository-Topic @ManyToMany 중간테이블 repo_topic 포함)를
--     운영해오다, 스키마를 Flyway로 조기 캡처(2주차)해 버전 관리로 전환.
--     이후 스키마 변경은 항상 새 V2, V3... 파일로 추가하고 이 파일은 수정 금지.
-- ══════════════════════════════════════════════════════════════

-- ──────────────────────────────────────
-- github_repository (GithubRepository.java)
-- ──────────────────────────────────────
CREATE TABLE github_repository (
    github_repository_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(255) NOT NULL,
    full_name             VARCHAR(255) NOT NULL,
    description           TEXT,
    language              VARCHAR(255),
    star_count            INTEGER NOT NULL,
    fork_count            INTEGER NOT NULL,
    open_issue_count      INTEGER NOT NULL,
    github_url            VARCHAR(255) NOT NULL,
    process_status        VARCHAR(20) NOT NULL,
    created_at            TIMESTAMP,
    updated_at            TIMESTAMP,
    CONSTRAINT uk_github_repository_full_name UNIQUE (full_name),
    CONSTRAINT ck_github_repository_process_status
        CHECK (process_status IN ('COLLECTED', 'EMBEDDED', 'FAILED'))
);

-- ──────────────────────────────────────
-- topics (Topic.java)
-- ──────────────────────────────────────
CREATE TABLE topics (
    topic_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_topics_name UNIQUE (name)
);

-- ──────────────────────────────────────
-- users (User.java)
-- ──────────────────────────────────────
CREATE TABLE users (
    user_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id         BIGINT NOT NULL,
    username          VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL,
    profile_image_url VARCHAR(255),
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP,
    CONSTRAINT uk_users_github_id UNIQUE (github_id)
);

-- ──────────────────────────────────────
-- repo_topic (GithubRepository.topics @ManyToMany @JoinTable)
-- 왜: JPA 연관관계 매핑용 순수 중간 테이블이라 BaseEntity(created_at/updated_at) 없음
-- 왜 복합 PK를 추가했는가: 엔티티 애노테이션만으로는 Hibernate가 PK/유니크를
--     강제하지 않지만, 동일 (repo, topic) 쌍 중복 삽입을 막기 위해 명시적으로 추가
-- ──────────────────────────────────────
CREATE TABLE repo_topic (
    repo_id  BIGINT NOT NULL,
    topic_id BIGINT NOT NULL,
    CONSTRAINT pk_repo_topic PRIMARY KEY (repo_id, topic_id)
);

-- ──────────────────────────────────────
-- issues (Issue.java)
-- ──────────────────────────────────────
CREATE TABLE issues (
    issue_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_issue_id BIGINT NOT NULL,
    title           VARCHAR(255) NOT NULL,
    state           VARCHAR(10) NOT NULL,
    repo_id         BIGINT NOT NULL,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    CONSTRAINT ck_issues_state CHECK (state IN ('OPEN', 'CLOSED'))
);

-- ──────────────────────────────────────
-- trend_scores (TrendScore.java, GithubRepository와 OneToOne)
-- ──────────────────────────────────────
CREATE TABLE trend_scores (
    trend_score_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id        BIGINT NOT NULL,
    score          DOUBLE PRECISION NOT NULL,
    calculated_at  TIMESTAMP NOT NULL,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    CONSTRAINT uk_trend_scores_repo_id UNIQUE (repo_id)
);

-- ──────────────────────────────────────
-- repo_embeddings (RepoEmbedding.java, GithubRepository와 OneToOne)
-- 왜 embedding_json이 TEXT인가: pgvector 확장 도입 전 임시 컬럼
--     (엔티티 TODO 주석 참조, 4주차에 vector(1536)으로 변경 예정 - V2에서 처리)
-- ──────────────────────────────────────
CREATE TABLE repo_embeddings (
    repo_embedding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id           BIGINT NOT NULL,
    embedding_json    TEXT,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP,
    CONSTRAINT uk_repo_embeddings_repo_id UNIQUE (repo_id)
);

-- ──────────────────────────────────────
-- user_favorites (UserFavorite.java)
-- ──────────────────────────────────────
CREATE TABLE user_favorites (
    user_favorite_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL,
    github_repository_id  BIGINT NOT NULL,
    notification_enabled  BOOLEAN NOT NULL,
    created_at            TIMESTAMP,
    updated_at            TIMESTAMP,
    CONSTRAINT uk_user_favorites_user_repo UNIQUE (user_id, github_repository_id)
);

-- ──────────────────────────────────────
-- user_skills (UserSkill.java)
-- ──────────────────────────────────────
CREATE TABLE user_skills (
    user_skill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    topic_id      BIGINT NOT NULL,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    CONSTRAINT uk_user_skills_user_topic UNIQUE (user_id, topic_id)
);

-- ══════════════════════════════════════════════════════════════
-- 외래키 제약조건
-- ══════════════════════════════════════════════════════════════

ALTER TABLE repo_topic
    ADD CONSTRAINT fk_repo_topic_repo
        FOREIGN KEY (repo_id) REFERENCES github_repository (github_repository_id);

ALTER TABLE repo_topic
    ADD CONSTRAINT fk_repo_topic_topic
        FOREIGN KEY (topic_id) REFERENCES topics (topic_id);

ALTER TABLE issues
    ADD CONSTRAINT fk_issues_repo
        FOREIGN KEY (repo_id) REFERENCES github_repository (github_repository_id);

ALTER TABLE trend_scores
    ADD CONSTRAINT fk_trend_scores_repo
        FOREIGN KEY (repo_id) REFERENCES github_repository (github_repository_id);

ALTER TABLE repo_embeddings
    ADD CONSTRAINT fk_repo_embeddings_repo
        FOREIGN KEY (repo_id) REFERENCES github_repository (github_repository_id);

ALTER TABLE user_favorites
    ADD CONSTRAINT fk_user_favorites_user
        FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE user_favorites
    ADD CONSTRAINT fk_user_favorites_repo
        FOREIGN KEY (github_repository_id) REFERENCES github_repository (github_repository_id);

ALTER TABLE user_skills
    ADD CONSTRAINT fk_user_skills_user
        FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE user_skills
    ADD CONSTRAINT fk_user_skills_topic
        FOREIGN KEY (topic_id) REFERENCES topics (topic_id);

-- ══════════════════════════════════════════════════════════════
-- 인덱스 (Day 10: language/star_count 동적 검색 조건 성능 검증 완료,
-- docs/troubleshooting.md "DB 인덱스 적용 전/후 비교" 참조)
-- ══════════════════════════════════════════════════════════════

CREATE INDEX idx_repo_language ON github_repository (language);
CREATE INDEX idx_repo_star_count ON github_repository (star_count);
